### ISSUE TITLE
Port not opening and general unreliability

### ISSUE THREAD

**Issue by Enduriel** [soxfor/qbittorrent-natmap#13]
I currently have the following stack up and running:
```yaml
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    network_mode: bridge
    cap_add:
      - NET_ADMIN
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8000:8000/tcp # Built-in HTTP control server
        # other containers ports
      - 6881:6881     # qBittorrent
      - 6881:6881/udp # qBittorrent
      - 50000:8080     # qBittorrent
    volumes:
      - /data/local/gluetun/data:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - VPN_ENDPOINT_IP=[removed]
      - VPN_ENDPOINT_PORT=51820
      - WIREGUARD_PUBLIC_KEY=[removed]
      - WIREGUARD_PRIVATE_KEY=[removed]
      - WIREGUARD_ADDRESSES=10.2.0.2/32
      # - FIREWALL_OUTBOUND_SUBNETS=192.168.1.0/24 I also tried this
      - TZ=Europe/London
      # - VPN_DNS_ADDRESS=${VPN_DNS_ADDRESS}
    restart: unless-stopped

  qbittorrent:
    container_name: qbittorrent
    image: cr.hotio.dev/hotio/qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/London
    network_mode: "service:gluetun"
    volumes:
      - /data/local/qbittorrent/config:/config
      - /data/external/badssd/torrents:/downloads
    restart: unless-stopped

  qbittorrent_natmap:
    container_name: qbittorrent_natmap
    image: ghcr.io/soxfor/qbittorrent-natmap:latest
    environment:
      - QBITTORRENT_SERVER=10.2.0.2
      - VPN_GATEWAY=10.2.0.1
      - QBITTORRENT_PORT=8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_healthy
      qbittorrent:
        condition: service_started
    restart: unless-stopped
```
Basically, everything seems to be working correctly, and the logs from qbittorrent-natmap suggest everything is going well:
```
$ docker logs qbittorrent_natmap
2023-05-12 11:37:14 | VPN container gluetun in healthy state!
2023-05-12 11:37:19 | qBittorrent SessionID Ok!
2023-05-12 11:37:19 | Public IP: [publicIP]
2023-05-12 11:37:19 | Configured Port: 53371
2023-05-12 11:37:19 | Active Port: 53371
2023-05-12 11:37:19 | Port OK (Act: 53371 Cfg: 53371)
2023-05-12 11:37:21 | IPTables rule added for port 53371 on gluetun container
2023-05-12 11:37:21 | NAT-PMP/UPnP Ok!
2023-05-12 11:37:21 | Sleeping for 5 minutes
2023-05-12 11:42:21 | qBittorrent SessionID Ok!
2023-05-12 11:42:21 | Public IP: [publicIP]
2023-05-12 11:42:21 | Configured Port: 53371
2023-05-12 11:42:21 | Active Port: 53371
2023-05-12 11:42:21 | Port OK (Act: 53371 Cfg: 53371)
2023-05-12 11:42:22 | NAT-PMP/UPnP Ok!
2023-05-12 11:42:22 | Sleeping for 5 minutes
```
but the port isn't actually connectable when I check it on [yougetsignal](https://www.yougetsignal.com/tools/open-ports/) and my private tracker tests reports that it responds with connection refused. At one point it was reporting the port as open, but even then it completely refused to seed, and the private tracker stated that it was leeching and not seeding.
I'm going to be honest I'm pretty new to the homelab thing so this is very much a learning process for me but this solution you set up seems like exactly what I was looking for and I hoped it would work perfectly but I can't seem to get it set up, I'm happy to try and debug this in any way, just let me know what you need.
I have also tried the linuxserver qbittorrent with the same result.
