### ISSUE TITLE
healthcheck makes it fail on wireguard

### ISSUE THREAD

**Issue by davidzx** [soxfor/qbittorrent-natmap#15]
hey
i got it working with gluetun, but the Linuxserver[dot]io wireguard container won't work. the natmap container just hangs on the health check.  would be nice to be able to turn off the health check, so it might work with other wireguard containers.

**Comment by heim3x** [comment]
You can add this healthcheck to the Wireguard container as a workaround.
```
    healthcheck:
      test: ["CMD-SHELL", "ip link show wg0 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
```
